config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :members, as: :users
  resources :members
  resources :events
  resources :locations
  resources :social

  resources :venues
  resources :sponsors
  resources :social_events
  resources :speakers
  resources :event_sessions
  resources :skill_sets
  resources :tickets  do    
    get 'activate', on: :member
  end

    namespace :admin do
      resources :home
    end
    namespace :api do
      namespace :v1 do
        devise_for :users
        resources :speakers
        resources :auth_test
        resources :event_sessions
        resources :events
        resources :tokens
        resources :check_ins
        resources :locations
        resources :messages
        resources :connections
        resources :tickets
        resources :ratings
        resources :venues
        resources :sponsors
        resources :social_events
        resources :skill_sets
        resources :profile do
            put 'photo_upload', on: :member 
            post 'add_session', on: :member        
            delete 'delete_session', on: :member        
        end
        resources :attendees
      end
    end
  # root 'home#index'
  root 'dash#index'
  get 'ping_api' => 'ping_api#index'

  

end

app/models/check_in.rb
class CheckIn < ActiveRecord::Base
  belongs_to :user
  belongs_to :event_session
end

app/models/connection.rb
class Connection < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, :class_name => "User"

end

app/models/csv_file.rb
class CsvFile < ActiveRecord::Base
  has_attached_file :file
  validates_attachment_content_type :file, :content_type => /.*/
end

app/models/event.rb
class Event < ActiveRecord::Base
	 has_and_belongs_to_many :locations
	 has_many :sessions
end

app/models/event_session.rb
class EventSession < ActiveRecord::Base
	attr_accessor :location_name
	attr_accessor :speakers_list
	attr_accessor :checked_in_users_list
	belongs_to :event
	belongs_to :location
	has_and_belongs_to_many :users
	has_and_belongs_to_many :speakers
	has_many :check_ins
	has_many :checked_in_users,:through => :check_ins,:source => "user"
	def attributes
	    super.merge('location_name' => self.location_name,'speakers_list' => self.speakers_list,'checked_in_users_list' => self.checked_in_users_list)
	end
	after_initialize do
		# if(!self.location.nil?)
	    	self.location_name = nil
	 #    end
	    self.checked_in_users_list = Array.new
	    # self.checked_in_users.each do |user|

	    #   self.checked_in_users_list << {:id => user.id, :name => user.name, :image => user.profile_image_url}
	    # end
	    self.speakers_list = Array.new
	    # self.speakers.each do |speaker|
	    #   self.speakers_list << {:id => speaker.id, :name => speaker.name, :image => speaker.profile_image_url}
	    # end
	end
end

app/models/hello_world.rb
class HelloWorld < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
	 has_and_belongs_to_many :events
	 has_many :sessions
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, :class_name => "User"
  belongs_to :recipient, :class_name => "User"
  attr_accessor :sender_profile
  def attributes
    super.merge('sender_profile' => self.sender_profile)
  end
  after_initialize do
  	if !self.sender.nil?
    self.sender_profile = {:name => self.sender.name, :avatar => self.sender.profile_image_url}
    else
    self.sender_profile = nil	
    end
  end
end

app/models/rating.rb
class Rating < ActiveRecord::Base

  belongs_to :user
  belongs_to :event_session

end

app/models/skill_set.rb
class SkillSet < ActiveRecord::Base
  has_and_belongs_to_many :users

end

app/models/social_event.rb
class SocialEvent < ActiveRecord::Base
end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
	attr_accessor :profile_image_url
	has_and_belongs_to_many :event_sessions
	has_attached_file :profile_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/default-profile-image.png"
	validates_attachment_content_type :profile_image, :content_type => /\Aimage\/.*\Z/
	def attributes
	  super.merge('profile_image_url' => self.profile_image_url)
	end
	after_initialize do
	  self.profile_image_url = self.profile_image.url
	end

	def name
		"#{self.first_name} #{self.last_name}"
	end
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  has_attached_file :csv_file, :default_url => "/images/default-profile-image.png"
  validates_attachment_content_type :csv_file, :content_type => /.*/
end 

app/models/token.rb
class Token < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # rolify
  attr_accessor :profile_image_url
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/default-profile-image.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  has_and_belongs_to_many :sessions, :class_name => "EventSession", :foreign_key => "user_id"
  has_and_belongs_to_many :skill_sets
  has_many :connections
  has_many :received_messages, :class_name => "Message", :foreign_key => "recipient_id"
  has_many :sent_messages, :class_name => "Message", :foreign_key => "sender_id"
  has_many :friends, :through => :connections
  has_many :check_ins
  # has_many :checked_in_sessions, :through => :check_ins, :source => "event_session"
  has_one :token, autosave: true
  has_many :ratings

  def attributes
    super.merge('profile_image_url' => self.profile_image_url)
    # super.merge('sessions' => self.sessions)
  end
  after_initialize do
    self.profile_image_url = self.avatar.url

  end

  def name
    "#{self.first_name} #{self.last_name}"
  end
  def find_by_api_token token
  	 User.where(:api_token => token).first
  end
end

app/models/venue.rb
class Venue < ActiveRecord::Base
end

app/helpers/dash_helper.rb
module DashHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Modev</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= yield :body_style %>">

	<%= yield :secondary %>
	<div class="<%= yield :content_style %>">
		<%= yield :notice %>
		<%= yield %>
	</div>
	<%= yield :footer %>
</body>
</html>

app/views/layouts/dash.html.erb
<%= content_for :body_style do %><% end %>
<%= content_for :content_style do %> main-content with-large-side-nav <% end %>
<%= content_for :secondary do %>
	<%= render "shared/side_nav" %>
	<%= render "shared/top_bar" %>
<% end %>
<%= content_for :notice do %>
	<% if !flash[:notice].blank? %>
		<div class="alert alert-success" role="alert">
			<p class="notice"><%= flash[:notice] %></p>
		</div>
	<% end %>
	<% if !flash[:alert].blank? %>
		<div class="alert alert-warning" role="alert">
			<p class="notice"><%= flash[:alert] %></p>
		</div>
	<% end %>
<% end %>

<%= render template: "layouts/application" %>

app/views/layouts/devise.html.erb
<%= content_for :body_style do %> log-me-in <% end %>
<%= content_for :secondary do %>
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
		<%= image_tag "modev-logo.png" , :class => "big-logo" %>
		</div>
	</div>
<% end %>
<%= content_for :footer do %>
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<% if !notice.nil? %>
				<h3 class="text-center"><%= notice %></h3>
			<% end %>
			<% if !alert.nil? %>
				<h3 class="text-center"><%= alert %></h3>
			<% end %>
		</div>
	</div>
<% end %>
<%= render template: "layouts/application" %>

app/views/shared/_side_nav.html.erb
<div class="side-nav">
<div class="side-nav-top-corner">
<%= image_tag "modev-logo.png" , :class => "side-bar-logo" %>
</div>
<div class="side-nav-menu">
<ul>
<%= link_to root_path do %>
	<li>
		<i class="glyphicon glyphicon-th-large"></i> Dashborad<i class="glyphicon glyphicon-chevron-right"></i>
	</li>
<% end%>
<%= link_to events_path do %>
	<li>
		<i class="glyphicon glyphicon-list-alt"></i> Events<i class="glyphicon glyphicon-chevron-right"></i>
	</li>
<% end%>
<%= link_to event_sessions_path do %>
	<li>
		<i class="glyphicon glyphicon-list-alt"></i> Sessions<i class="glyphicon glyphicon-chevron-right"></i>
	</li>
<% end%>
<%= link_to locations_path do %>
	<li>
		<i class="glyphicon glyphicon-list-alt"></i> Locations<i class="glyphicon glyphicon-chevron-right"></i>
	</li>
<% end%>
<%= link_to skill_sets_path do %>
	<li>
		<i class="glyphicon glyphicon-list-alt"></i> Skillsets<i class="glyphicon glyphicon-chevron-right"></i>
	</li>
<% end%>
<%= link_to sponsors_path do %>
	<li>
		<i class="glyphicon glyphicon-list-alt"></i> Sponsors<i class="glyphicon glyphicon-chevron-right"></i>
	</li>
<% end%>
<%= link_to venues_path do %>
	<li>
		<i class="glyphicon glyphicon-list-alt"></i> Venues<i class="glyphicon glyphicon-chevron-right"></i>
	</li>
<% end%>
<%= link_to social_events_path do %>
	<li>
		<i class="glyphicon glyphicon-list-alt"></i> Social<i class="glyphicon glyphicon-chevron-right"></i>
	</li>
<% end%>
<%= link_to speakers_path do %>
	<li>
		<i class="glyphicon glyphicon-list-alt"></i> Speakers<i class="glyphicon glyphicon-chevron-right"></i>
	</li>
<% end%>
<%= link_to members_path do %>
	<li>
		<i class="glyphicon glyphicon-user"></i> Users<i class="glyphicon glyphicon-chevron-right"></i>
	</li>
<% end%>
<%= link_to tickets_path do %>
	<li>
		<i class="glyphicon glyphicon-list-alt"></i> Registration Import<i class="glyphicon glyphicon-chevron-right"></i>
	</li>
<% end%>
</ul>
</div>
</div>

app/views/shared/_top_bar.html.erb
<div class="top-bar with-large-side-nav">
	<div class="col-md-4">
		<div class="top-bar-profile-image">
			<%= image_tag current_user.avatar.url, :class => "img-responsive" %>
		</div>
		<div class="top-bar-profile-info">

			<h3><%= "#{current_user.first_name} #{current_user.last_name}" %></h3>
	  		<h4>Logged in as <strong><%= current_user.email %></strong></h4>
			
		</div>
	</div>
	<div class="col-md-8 top-bar-profile-menu">
		<ul class="nav navbar-nav navbar-right">

			  <li>
			  	<%= link_to destroy_user_session_path, method: :delete, :class => 'navbar-link' do %>
			  		<i class="glyphicon glyphicon-log-out"></i> Logout
			  	<% end %>
			  </li>
		</ul>
	</div>
</div>