config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :members, as: :users
  resources :members
  resources :events
  resources :locations
  resources :social

  resources :venues
  resources :sponsors
  resources :social_events
  resources :speakers
  resources :event_sessions
  resources :skill_sets
  resources :tickets  do    
    get 'activate', on: :member
  end

    namespace :admin do
      resources :home
    end
    namespace :api do
      namespace :v1 do
        devise_for :users
        resources :speakers
        resources :auth_test
        resources :event_sessions
        resources :events
        resources :tokens
        resources :check_ins
        resources :locations
        resources :messages
        resources :connections
        resources :tickets
        resources :ratings
        resources :venues
        resources :sponsors
        resources :social_events
        resources :skill_sets
        resources :profile do
            put 'photo_upload', on: :member 
            post 'add_session', on: :member        
            delete 'delete_session', on: :member        
        end
        resources :attendees
      end
    end
  # root 'home#index'
  root 'dash#index'
  get 'ping_api' => 'ping_api#index'

  

end

app/models/check_in.rb
class CheckIn < ActiveRecord::Base
  belongs_to :user
  belongs_to :event_session
end

app/models/connection.rb
class Connection < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, :class_name => "User"

end

app/models/csv_file.rb
class CsvFile < ActiveRecord::Base
  has_attached_file :file
  validates_attachment_content_type :file, :content_type => /.*/
end

app/models/event.rb
class Event < ActiveRecord::Base
	 has_and_belongs_to_many :locations
	 has_many :sessions
end

app/models/event_session.rb
class EventSession < ActiveRecord::Base
	attr_accessor :location_name
	attr_accessor :speakers_list
	attr_accessor :checked_in_users_list
	belongs_to :event
	belongs_to :location
	has_and_belongs_to_many :users
	has_and_belongs_to_many :speakers
	has_many :check_ins
	has_many :checked_in_users,:through => :check_ins,:source => "user"
	def attributes
	    super.merge('location_name' => self.location_name,'speakers_list' => self.speakers_list,'checked_in_users_list' => self.checked_in_users_list)
	end
	after_initialize do
		# if(!self.location.nil?)
	    	self.location_name = nil
	 #    end
	    self.checked_in_users_list = Array.new
	    # self.checked_in_users.each do |user|

	    #   self.checked_in_users_list << {:id => user.id, :name => user.name, :image => user.profile_image_url}
	    # end
	    self.speakers_list = Array.new
	    # self.speakers.each do |speaker|
	    #   self.speakers_list << {:id => speaker.id, :name => speaker.name, :image => speaker.profile_image_url}
	    # end
	end
end

app/models/hello_world.rb
class HelloWorld < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
	 has_and_belongs_to_many :events
	 has_many :sessions
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, :class_name => "User"
  belongs_to :recipient, :class_name => "User"
  attr_accessor :sender_profile
  def attributes
    super.merge('sender_profile' => self.sender_profile)
  end
  after_initialize do
  	if !self.sender.nil?
    self.sender_profile = {:name => self.sender.name, :avatar => self.sender.profile_image_url}
    else
    self.sender_profile = nil	
    end
  end
end

app/models/rating.rb
class Rating < ActiveRecord::Base

  belongs_to :user
  belongs_to :event_session

end

app/models/skill_set.rb
class SkillSet < ActiveRecord::Base
  has_and_belongs_to_many :users

end

app/models/social_event.rb
class SocialEvent < ActiveRecord::Base
end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
	attr_accessor :profile_image_url
	has_and_belongs_to_many :event_sessions
	has_attached_file :profile_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/default-profile-image.png"
	validates_attachment_content_type :profile_image, :content_type => /\Aimage\/.*\Z/
	def attributes
	  super.merge('profile_image_url' => self.profile_image_url)
	end
	after_initialize do
	  self.profile_image_url = self.profile_image.url
	end

	def name
		"#{self.first_name} #{self.last_name}"
	end
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  has_attached_file :csv_file, :default_url => "/images/default-profile-image.png"
  validates_attachment_content_type :csv_file, :content_type => /.*/
end 

app/models/token.rb
class Token < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # rolify
  attr_accessor :profile_image_url
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/default-profile-image.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  has_and_belongs_to_many :sessions, :class_name => "EventSession", :foreign_key => "user_id"
  has_and_belongs_to_many :skill_sets
  has_many :connections
  has_many :received_messages, :class_name => "Message", :foreign_key => "recipient_id"
  has_many :sent_messages, :class_name => "Message", :foreign_key => "sender_id"
  has_many :friends, :through => :connections
  has_many :check_ins
  # has_many :checked_in_sessions, :through => :check_ins, :source => "event_session"
  has_one :token, autosave: true
  has_many :ratings

  def attributes
    super.merge('profile_image_url' => self.profile_image_url)
    # super.merge('sessions' => self.sessions)
  end
  after_initialize do
    self.profile_image_url = self.avatar.url

  end

  def name
    "#{self.first_name} #{self.last_name}"
  end
  def find_by_api_token token
  	 User.where(:api_token => token).first
  end
end

app/models/venue.rb
class Venue < ActiveRecord::Base
end

app/controllers/api/v1/event_sessions_controller.rb
class Api::V1::EventSessionsController < Api::V1::BaseApiController
	# before_action :is_token_valid?

	def index
		@event_sessions = EventSession.includes(:location,:checked_in_users,:speakers).all
		@sessions = format_sessions @event_sessions

		render :json => @sessions.as_json
	end
	def show
		#show user sessions here
	end
end

app/controllers/event_sessions_controller.rb
class EventSessionsController < ApplicationController
	layout "dash"
	before_action :is_user_logged_in?
	def index
		@event_sessions = EventSession.all
	end
	def new
		@event_session = EventSession.new
	end
	def show
		begin
		@event_session = EventSession.find(params['id'])
		rescue Exception => e
			flash[:alert] = e
			redirect_to event_sessions_path
		end
	end
	def edit
		begin
		@event_session = EventSession.find(params['id'])
		rescue Exception => e
			flash[:alert] = e
			redirect_to event_sessions_path
		end
	end
	def create
		@event_session = EventSession.new(session_params)
		begin
			@event_session.save!
		rescue Exception => e
			flash[:error] = e
		end
		if flash[:error].nil?
			flash[:notice] = "EventSession Created!"
			redirect_to event_sessions_path
		else
			render 'new'
		end
	end
	def update
		unless @event_session = EventSession.find(params['id'])
			flash[:notice] = "EventSession Does not exist"
			redirect_to event_sessions_path
		end
		if @event_session.update_attributes session_params
			flash[:notice] = "EventSession Updated"
			redirect_to event_sessions_path
		else
			flash[:error] = "Someting Went wrong"
			redirect_to edit_event_session_path(@event_session)
		end
	end
	def destroy
		if @event_session = EventSession.find(params['id']) then
			@event_session.destroy
			flash[:notice] = "EventSession Deleted!"
		end
		redirect_to event_sessions_path
	end
	private
	def session_params
		params.require(:event_session).permit(:name,:description,:color,:start_date,:duration,:event_id,:physical_location,:location_id,:speaker_ids => [])
	end
end

app/helpers/api/v1/event_sessions_helper.rb
module Api::V1::EventSessionsHelper
end

app/helpers/dash_helper.rb
module DashHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_sessions/_session_form.html.erb
<div class="row">
  	 <%= simple_form_for @event_session  do |f| %>
		
	<div class="col-md-4">
		<div class="form-input">
		<%= f.input :name %>
		<%= f.input :description %>
		<%= f.input :start_date, :input_html => { :class => 'date_picker' } %>
		<%= f.input :color %>
		<%= f.input :duration %>
		<%= f.input :physical_location %>
		<%= f.association :event %>
		<%= f.association :location %>
		<%= f.association :speakers,   as: :check_boxes %>
	  	<%= f.button :submit %>
	  	</div>
	</div>
	 <% end %>
</div>

app/views/event_sessions/edit.html.erb
<%= link_to 'back',event_sessions_path %>
<h2>Update Session Details</h2>
<%= render 'session_form' %>

app/views/event_sessions/index.html.erb
<h1>Sessionss:</h1>
<%= link_to 'Create new Sessions', new_event_session_path %>
<div class="table-responsive">
	<table class="table table-striped">
	  <thead>
	    <tr>
	      <th style="width:5px;"></th>
	      <th class="col-name">Name</th>
	      <th class="col-name">Description</th>
	      <th class="col-name">Start Date</th>
	      <th class="col-name">Duration</th>
	      <th class="col-name">Event</th>
	      <th class="col-name">Physical location</th>
	      <th class="col-name">Location</th>
	      <th class="col-name">speakers</th>
	    </tr>
	  </thead>
	  <tbody>
	  <% for session in @event_sessions %>
	    <tr>
	     	<td style="width: 25px;min-height: 50px;margin:0;padding0;"><div style="width: 100%;height: 100%;margin:0;padding0; background-color: <%= session.color %>">&nbsp;</div></td>
	     	<td><%= link_to session.name, event_session_path(session) %></td>
	     	<td><%= session.description %></td>
	     	<td><%= session.start_date %></td>
	     	<td><%= session.duration %></td>
	     	<% if !session.event.nil? %>
	     	<td><%= session.event.name %></td>
			<% end %>
	     	<td><%= session.physical_location %></td>

	     	<% if !session.location.nil? %>
	     	<td><%= session.location.name %></td>
			<% end %>
			<td>
			<% for speaker in session.speakers %>
				<%= speaker.name %> <br/>
			<% end %>
			</td>
			<td><%= link_to 'edit',edit_event_session_path(session) %> | 
			<%= link_to 'Delete', event_session_path(session), method: :delete %></td>
	    </tr>
	  <% end %>
	  </tbody>
	</table>
</div>

app/views/event_sessions/new.html.erb
<%= link_to 'back',event_sessions_path %>
<h2>Create a new Session</h2>
<%= render 'session_form' %>

app/views/event_sessions/show.html.erb
<%= link_to 'back',event_sessions_path %>
<h1>Session Details</h1>
<h2>Session Name: <strong><%= @event_session.name %></strong></h2>
<h2>Session Description: <strong><%= @event_session.description %></strong></h2>
<h2>Start Date: <strong><%= @event_session.start_date %></strong></h2>
<h2>Physical Location: <strong><%= @event_session.physical_location %></strong></h2>
<h2>Duration: <strong><%= @event_session.duration %></strong></h2>
<h2>Color: <strong><%= @event_session.color %></strong></h2>
<h2>Event Name: <strong><%= @event_session.event.name %></strong></h2>
<h2>Location: <strong><%= @event_session.location.name%></strong></h2>
<h2>Speakers:</h2>
<% for speaker in @event_session.speakers %>
<%= speaker.name %> <br/>
<% end %>