config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :members, as: :users
  resources :members
  resources :events
  resources :locations
  resources :social

  resources :venues
  resources :sponsors
  resources :social_events
  resources :speakers
  resources :event_sessions
  resources :skill_sets
  resources :tickets  do    
    get 'activate', on: :member
  end

    namespace :admin do
      resources :home
    end
    namespace :api do
      namespace :v1 do
        devise_for :users
        resources :speakers
        resources :auth_test
        resources :event_sessions
        resources :events
        resources :tokens
        resources :check_ins
        resources :locations
        resources :messages
        resources :connections
        resources :tickets
        resources :ratings
        resources :venues
        resources :sponsors
        resources :social_events
        resources :skill_sets
        resources :profile do
            put 'photo_upload', on: :member 
            post 'add_session', on: :member        
            delete 'delete_session', on: :member        
        end
        resources :attendees
      end
    end
  # root 'home#index'
  root 'dash#index'
  get 'ping_api' => 'ping_api#index'

  

end

app/models/check_in.rb
class CheckIn < ActiveRecord::Base
  belongs_to :user
  belongs_to :event_session
end

app/models/connection.rb
class Connection < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, :class_name => "User"

end

app/models/csv_file.rb
class CsvFile < ActiveRecord::Base
  has_attached_file :file
  validates_attachment_content_type :file, :content_type => /.*/
end

app/models/event.rb
class Event < ActiveRecord::Base
	 has_and_belongs_to_many :locations
	 has_many :sessions
end

app/models/event_session.rb
class EventSession < ActiveRecord::Base
	attr_accessor :location_name
	attr_accessor :speakers_list
	attr_accessor :checked_in_users_list
	belongs_to :event
	belongs_to :location
	has_and_belongs_to_many :users
	has_and_belongs_to_many :speakers
	has_many :check_ins
	has_many :checked_in_users,:through => :check_ins,:source => "user"
	def attributes
	    super.merge('location_name' => self.location_name,'speakers_list' => self.speakers_list,'checked_in_users_list' => self.checked_in_users_list)
	end
	after_initialize do
		# if(!self.location.nil?)
	    	self.location_name = nil
	 #    end
	    self.checked_in_users_list = Array.new
	    # self.checked_in_users.each do |user|

	    #   self.checked_in_users_list << {:id => user.id, :name => user.name, :image => user.profile_image_url}
	    # end
	    self.speakers_list = Array.new
	    # self.speakers.each do |speaker|
	    #   self.speakers_list << {:id => speaker.id, :name => speaker.name, :image => speaker.profile_image_url}
	    # end
	end
end

app/models/hello_world.rb
class HelloWorld < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
	 has_and_belongs_to_many :events
	 has_many :sessions
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, :class_name => "User"
  belongs_to :recipient, :class_name => "User"
  attr_accessor :sender_profile
  def attributes
    super.merge('sender_profile' => self.sender_profile)
  end
  after_initialize do
  	if !self.sender.nil?
    self.sender_profile = {:name => self.sender.name, :avatar => self.sender.profile_image_url}
    else
    self.sender_profile = nil	
    end
  end
end

app/models/rating.rb
class Rating < ActiveRecord::Base

  belongs_to :user
  belongs_to :event_session

end

app/models/skill_set.rb
class SkillSet < ActiveRecord::Base
  has_and_belongs_to_many :users

end

app/models/social_event.rb
class SocialEvent < ActiveRecord::Base
end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
	attr_accessor :profile_image_url
	has_and_belongs_to_many :event_sessions
	has_attached_file :profile_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/default-profile-image.png"
	validates_attachment_content_type :profile_image, :content_type => /\Aimage\/.*\Z/
	def attributes
	  super.merge('profile_image_url' => self.profile_image_url)
	end
	after_initialize do
	  self.profile_image_url = self.profile_image.url
	end

	def name
		"#{self.first_name} #{self.last_name}"
	end
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  has_attached_file :csv_file, :default_url => "/images/default-profile-image.png"
  validates_attachment_content_type :csv_file, :content_type => /.*/
end 

app/models/token.rb
class Token < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # rolify
  attr_accessor :profile_image_url
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/default-profile-image.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  has_and_belongs_to_many :sessions, :class_name => "EventSession", :foreign_key => "user_id"
  has_and_belongs_to_many :skill_sets
  has_many :connections
  has_many :received_messages, :class_name => "Message", :foreign_key => "recipient_id"
  has_many :sent_messages, :class_name => "Message", :foreign_key => "sender_id"
  has_many :friends, :through => :connections
  has_many :check_ins
  # has_many :checked_in_sessions, :through => :check_ins, :source => "event_session"
  has_one :token, autosave: true
  has_many :ratings

  def attributes
    super.merge('profile_image_url' => self.profile_image_url)
    # super.merge('sessions' => self.sessions)
  end
  after_initialize do
    self.profile_image_url = self.avatar.url

  end

  def name
    "#{self.first_name} #{self.last_name}"
  end
  def find_by_api_token token
  	 User.where(:api_token => token).first
  end
end

app/models/venue.rb
class Venue < ActiveRecord::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
	layout 'dash'
	before_action :is_user_logged_in?
	def index
		@member = User.new

		@members = User.all
		# @friendly = DateReader.friendly_date
	end
	def new
		@member = User.new
	end
	def show
		render nil
	end
	def create
		@members = User.all
		begin
			@member = User.new user_params
			@member.save!
			flash[:notice] = "User Created!"
		rescue Exception => e
			flash[:error] = e
		end
		if flash[:error].nil?
			render 'index'
		else
			redirect_to members_path
		end
	end
	def edit
		unless @member = User.find(params['id'])
			flash[:notice] = "User Does not exist"
			redirect_to members_path
		end
	end
	def update
		unless @member = User.find(params['id'])
			flash[:notice] = "User Does not exist"
			redirect_to members_path
		end
		if @member.update_attributes user_params
			flash[:notice] = "User Updated"
			redirect_to members_path
		else
			flash[:error] = "Someting Went wrong"
			redirect_to edit_member_path(@member)
		end
	end
	def destroy
		if @member = User.find(params['id']) then
			@member.destroy
			flash[:notice] = "User Deleted!"
		end
		redirect_to members_path
	end
	private
	def user_params
		if params["user"]["password"].blank?
		params.require(:user).permit( :first_name, :last_name, :title, :company, :avatar, :email) 
		else
		params.require(:user).permit( :first_name, :last_name, :title, :company, :avatar, :email, :password) 
		end
	end
end

app/helpers/dash_helper.rb
module DashHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/members/_create_new_user_inline.html.erb
<div class="row">
  	 <%= simple_form_for @member, html: {class: 'form-inline'} do |f| %>
		<%= f.error_notification %>
	<div class="col-md-12">
	
		<div class="form-plus">	
		<i class="glyphicon glyphicon glyphicon-plus text-muted"></i>
		</div>
		<div class="form-image-upload rounded-image-in-table">
				<%= image_tag @member.avatar.url, :class => "img-responsive" %>
		</div>
		<div class="form-input">
		<%= f.input :first_name, placeholder: 'First Name', label: false %>
		<%= f.input :last_name, placeholder: 'Last Name', label: false  %>
		<%= f.input :title, placeholder: 'Title', label: false  %>
		<%= f.input :company, placeholder: 'Company', label: false  %>
		<%= f.input :email, placeholder: 'user@email.com', label: false , input_html: {autocomplete: 'off'} %>
		<%= f.input :password, placeholder: 'password', label: false %>
	  	<%= f.button :submit %>
	  	</div>
	</div>
	<div class="file-upload">
	<%= f.input :avatar, label: 'Profile Image'%>
	</div>
	 <% end %>
</div>

app/views/members/edit.html.erb
<div class="row">
<h2>Edit Info:</h2>
  	 <%= simple_form_for @member, html: { } do |f| %>
		<%= f.error_notification %>
	<div class="col-md-12">

		<div class="form-image-upload rounded-image-in-table">
				<%= image_tag @member.avatar.url, :class => "img-responsive" %>
		</div>
				<%= f.input :avatar, label: 'Profile Image'%>
		<div class="form-input">
		<%= f.input :first_name, placeholder: 'First Name', label: false %>
		<%= f.input :last_name, placeholder: 'Last Name', label: false  %>
		<%= f.input :email, placeholder: 'user@email.com', label: false , input_html: {autocomplete: 'off'} %>
		<%= f.input :password, placeholder: 'password', label: false %>
	  	<%= f.button :submit %>
	  	</div>
	</div>
	<div class="file-upload">
	</div>
	 <% end %>
</div>

app/views/members/index.html.erb
<h2 class="sub-header">Team Management:</h2>
<h3>Add A New Menber:</h3>
<%= render "create_new_user_inline" %>

<h2>List of All Team Menbers:</h2>
<div class="table-responsive user-table">
	<table class="table table-striped member-list">
	  <thead>
	    <tr>
	      <th class="col-profile"></th>
	      <th class="col-name">Name</th>
	      <th class="col-email">Email</th>
	      <th class="col-email">Title</th>
	      <th class="col-email">Company</th>
	      <th class="col-last-active">Last Active</th>
	      <th class=""></th>
	      <th class="col-links"></th>
	    </tr>
	  </thead>
	  <tbody>
	  <% for member in @members %>
	    <tr>
	      <td>
			<div class="rounded-image-in-table">
				<%= image_tag member.avatar.url, :class => "img-responsive" %>
			</div>	
	      
	      </td>
	      <td><%= member.name %></td>
	      <td><%= member.email %></td>
	      <td><%= member.title %></td>
	      <td><%= member.company %></td>
	      <td class="last_active"><%= friendly_d member.created_at %></td>
	      <td></td>
	      <td><%= link_to 'Edit', edit_member_path(member) %> | 
	      <%= link_to 'Delete', member_path(member), method: :delete %></td>
	    </tr>
	  <% end %>
	  </tbody>
	</table>
</div>

app/views/members/new.html.erb
<h1>Create a new User:</h1>
<div class="row">
	<div class="col-md-6">	
  	 <%= simple_form_for @member do |f| %>
		<%= f.error_notification %>
		<%= f.input :first_name %>
		<%= f.input :last_name %>
		<%= f.input :title, placeholder: 'Title', label: false  %>
		<%= f.input :company, placeholder: 'Company', label: false  %>
		<%= f.input :email %>
		<%= f.input :password %>
		<%= f.input :password_confirmation %>
	  	<%= f.button :submit %>
	 <% end %>
	</div>
</div>